openapi: 3.1.0
info:
  title: Pulso do Mercado API
  description: Documentação da API Pulso do Mercado
  version: 1.0.0
paths:
  /:
    get:
      summary: Read Root
      operationId: read_root__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/selic-meta:
    get:
      tags:
        - SELIC
      summary: Get Selic Meta
      operationId: get_selic_meta_api_selic_meta_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelicMeta'
  /api/ipca:
    get:
      tags:
        - IPCA
      summary: Get Ipca
      operationId: get_ipca_api_ipca_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/cdi:
    get:
      tags:
        - CDI
      summary: Get Cdi
      operationId: get_cdi_api_cdi_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CDI'
  /api/ibovespa:
    get:
      tags:
        - IBOVESPA
      summary: Get Ibovespa
      operationId: get_ibovespa_api_ibovespa_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ibovespa'
  /api/sp500:
    get:
      tags:
        - S&P 500
      summary: Get Sp500
      operationId: get_sp500_api_sp500_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SP500'
  /api/:
    get:
      tags:
        - USD/BRL
      summary: Cotação mockada do Dólar Comercial (USD/BRL)
      operationId: get_usdbrl_api__get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/treasury-10y:
    get:
      tags:
        - US Treasury
      summary: Get Treasury Yield
      operationId: get_treasury_yield_api_treasury_10y_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Treasury10Y'
  /api/users/users:
    post:
      tags:
        - Usuários
      summary: Create User
      operationId: create_user_api_users_users_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRead'
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/users/users/{user_id}:
    get:
      tags:
        - Usuários
      summary: Read User
      operationId: read_user_api_users_users__user_id__get
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            title: User Id
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRead'
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
        - Usuários
      summary: Update User
      operationId: update_user_api_users_users__user_id__put
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            title: User Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRead'
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
        - Usuários
      summary: Delete User
      operationId: delete_user_api_users_users__user_id__delete
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            title: User Id
      responses:
        "204":
          description: Successful Response
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/token/api/token:
    post:
      tags:
        - Autenticação
      summary: Login
      operationId: login_api_token_api_token_post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_api_token_api_token_post'
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/me:
    get:
      tags:
        - Usuário
      summary: Get Me
      operationId: get_me_api_me_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
        - OAuth2PasswordBearer: []
  /api/api/protected:
    get:
      tags:
        - Protegido
      summary: Protected Route
      operationId: protected_route_api_api_protected_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
        - OAuth2PasswordBearer: []
  /api/webscraping/infomoney:
    get:
      tags:
        - Webscraping
        - WEBSCRAPING
      summary: Get Infomoney News
      operationId: get_infomoney_news_api_webscraping_infomoney_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/status:
    get:
      tags:
        - Status
      summary: Get Status
      operationId: get_status_api_status_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
