components:
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  description: "API de dados econ\xF4micos e financeiros com autentica\xE7\xE3o JWT"
  title: Pulso do Mercado API
  version: 1.0.0
openapi: 3.1.0
paths: {}
security:
- BearerAuth: []
