name: CI - Pulso do Mercado API

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ./

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze

      - name: Seed demo user
        run: python app/scripts/seed_users.py

      - name: Rodar testes com Pytest e Coverage
        run: coverage run -m pytest tests

      - name: Relatório de cobertura
        run: coverage report -m

      - name: Verificar cobertura mínima (exemplo 75%)
        run: coverage report --fail-under=75

      - name: Deploy no Render
        if: github.event_name == 'push' && success()
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
